## Lab 03 - ANN DL - MLP (Multi-Layered Perceptron) for Classification

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.datasets import make_regression
from sklearn import metrics
from sklearn import decomposition
from sklearn import manifold
from tqdm.notebook import trange, tqdm

#TensorFlow and Keras Libraries
import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model
import torch
from torchvision import transforms
from tensorflow.keras.utils import to_categorical
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data
import torchvision
import torchvision.datasets as datasets
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os

# Hiding the warnings
import warnings
warnings.filterwarnings('ignore')

# Extra Libraries
import copy
import random
import time

In [2]:
data_path = "DataBase/Class_Data/house-prices.csv"
df = pd.read_csv(data_path)

In [3]:
df.head()

   Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300  1790         2          2       2    No         East
1     2  114200  2030         4          2       3    No         East
2     3  114800  1740         3          2       1    No         East
3     4   94700  1980         3          2       3    No         East
4     5  119800  2130         3          3       3    No         East

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Home,128.0,64.500000,37.094474,1.0,32.75,64.5,96.25,128.0
Price,128.0,130427.343750,26868.770371,69100.0,111325.00,125950.0,148250.00,211200.0
SqFt,128.0,2000.937500,211.572431,1450.0,1880.00,2000.0,2140.00,2590.0
Bedrooms,128.0,3.023438,0.725951,2.0,3.00,3.0,3.00,5.0
Bathrooms,128.0,2.445312,0.514492,2.0,2.00,2.0,3.00,4.0
Offers,128.0,2.578125,1.069324,1.0,2.00,3.0,3.00,6.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Home          128 non-null    int64
 1   Price         128 non-null    int64
 2   SqFt          128 non-null    int64
 3   Bedrooms      128 non-null    int64
 4   Bathrooms     128 non-null    int64
 5   Offers        128 non-null    int64
 6   Brick         128 non-null    object
 7   Neighborhood  128 non-null    object
dtypes: int64(6), object(2)
memory usage: 8.1+ KB

In [6]:
df.isna().sum()

Home            0
Price           0
SqFt            0
Bedrooms        0
Bathrooms       0
Offers          0
Brick           0
Neighborhood    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
# Possible target for classification : 
# A) Brick -> Binary Class Classification
# B) Neighborhood -> Multi Class Classification

In [9]:
cat_col = []
for i in df.columns:
    if df[i].dtype == 'O':
        cat_col.append(i)

cat_col

['Brick', 'Neighborhood']

In [10]:
df['Brick'].value_counts()

Brick
No     86
Yes    42
Name: count, dtype: int64

In [11]:
df['Neighborhood'].value_counts()

Neighborhood
East     45
North    44
West     39
Name: count, dtype: int64

In [12]:
df[cat_col].nunique()

Brick           2
Neighborhood    3
dtype: int64

In [13]:
# Now using Label Encoder :
le1 = LabelEncoder()
df['Brick'] = le1.fit_transform(df['Brick'])
df['Brick'].unique()

array([0, 1])

In [14]:
le2 = LabelEncoder()
df['Neighborhood'] = le2.fit_transform(df['Neighborhood'])
df['Neighborhood'].unique()

array([0, 1, 2])

In [15]:
# Dropping column - "Home"
df.drop('Home',axis=1,inplace=True)

In [16]:
# Standardization of data :
sc1 = MinMaxScaler()
df[['Price']] = sc1.fit_transform(df[['Price']])

sc2 = MinMaxScaler()
df[['SqFt']] = sc2.fit_transform(df[['SqFt']])

In [17]:
df['Price'] = round(df['Price'],2)
df['SqFt'] = round(df['SqFt'],2)

In [18]:
df.head()

   Price  SqFt  Bedrooms  Bathrooms  Offers  Brick  Neighborhood
0   0.32  0.30         2          2       2      0             0
1   0.32  0.51         4          2       3      0             0
2   0.32  0.25         3          2       1      0             0
3   0.18  0.46         3          2       3      0             0
4   0.36  0.60         3          3       3      0             0

In [19]:
# Binary Class Classification :
X = df.drop('Brick',axis=1)
y = df['Brick']

In [20]:
# Train-Test Split :
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)
print("X_train shape : ",X_train.shape)
print("X_test shape : ",X_test.shape)
print("y_train shape : ",y_train.shape)
print("y_test shape : ",y_test.shape)

X_train shape :  (85, 6)
X_test shape :  (43, 6)
y_train shape :  (85,)
y_test shape :  (43,)

In [21]:
# Building MLP model for Binary Class Classification :
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(45,activation='relu',input_dim = 6))
model.add(tf.keras.layers.Dense(25,activation='relu'))
model.add(tf.keras.layers.Dense(15,activation='relu'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

In [22]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adam', metrics=['BinaryAccuracy'])
history = model.fit(X_train, y_train, epochs=500)

Epoch 1/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - BinaryAccuracy: 0.2662 - loss: 0.8247
Epoch 2/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.2701 - loss: 0.7667
Epoch 3/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.2701 - loss: 0.7239
Epoch 4/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.6086 - loss: 0.6855
Epoch 5/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7397 - loss: 0.6635
Epoch 6/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7299 - loss: 0.6514
Epoch 7/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7143 - loss: 0.6446
Epoch 8/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7221 - loss: 0.6360
Epoch 9/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.6987 - loss: 0.6329
Epoch 10/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.6987 - loss: 0.6287
Epoch 11/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7065 - loss: 0.6208
Epoch 12/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7299 - loss: 0.6046
Epoch 13/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.6948 - loss: 0.6166
Epoch 14/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.7026 - loss: 0.6150
Epoch 15/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - BinaryAccuracy: 0.7143 - loss: 0.5991
Epoch 16/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - BinaryAccuracy: 0.6948 - loss: 0.6116
Epoch 17/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.7338 - loss: 0.5903
Epoch 18/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7338 - loss: 0.5798
Epoch 19/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7182 - loss: 0.5903
Epoch 20/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7065 - loss: 0.6106
Epoch 21/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7260 - loss: 0.5785
Epoch 22/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - BinaryAccuracy: 0.7143 - loss: 0.5924
Epoch 23/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.7026 - loss: 0.6014
Epoch 24/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.6948 - loss: 0.6051
Epoch 25/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7065 - loss: 0.6054
Epoch 26/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7026 - loss: 0.6056
Epoch 27/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7182 - loss: 0.5892
Epoch 28/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7065 - loss: 0.5956
Epoch 29/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7377 - loss: 0.5695
Epoch 30/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7338 - loss: 0.5705
Epoch 31/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - BinaryAccuracy: 0.7026 - loss: 0.6028
Epoch 32/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.7377 - loss: 0.5673
Epoch 33/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7299 - loss: 0.5711
Epoch 34/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7026 - loss: 0.5917
Epoch 35/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7416 - loss: 0.5609
Epoch 36/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7221 - loss: 0.5822
Epoch 37/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7377 - loss: 0.5628
Epoch 38/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.6791 - loss: 0.6210
Epoch 39/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.7416 - loss: 0.5646
Epoch 40/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - BinaryAccuracy: 0.7260 - loss: 0.5724
Epoch 41/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7416 - loss: 0.5539
Epoch 42/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7065 - loss: 0.5839
Epoch 43/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7338 - loss: 0.5653
Epoch 44/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7143 - loss: 0.5832
Epoch 45/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.7026 - loss: 0.5902
Epoch 46/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7221 - loss: 0.5706
Epoch 47/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.7260 - loss: 0.5715
Epoch 48/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.6909 - loss: 0.5994
Epoch 49/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7026 - loss: 0.5892
Epoch 50/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7260 - loss: 0.5714
Epoch 51/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.6987 - loss: 0.5937
Epoch 52/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.7026 - loss: 0.6013
Epoch 53/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.6987 - loss: 0.5933
Epoch 54/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - BinaryAccuracy: 0.7377 - loss: 0.5368
Epoch 55/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7260 - loss: 0.5582
Epoch 56/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.6987 - loss: 0.5855
Epoch 57/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - BinaryAccuracy: 0.7455 - loss: 0.5479
Epoch 58/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.6830 - loss: 0.5980
Epoch 59/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7455 - loss: 0.5253
Epoch 60/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7182 - loss: 0.5687
Epoch 61/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7202 - loss: 0.5634
Epoch 62/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7124 - loss: 0.5699
Epoch 63/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7280 - loss: 0.5647
Epoch 64/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.6752 - loss: 0.5819
Epoch 65/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7358 - loss: 0.5486
Epoch 66/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.6928 - loss: 0.5821
Epoch 67/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.7377 - loss: 0.5375
Epoch 68/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.7182 - loss: 0.5618
Epoch 69/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7651 - loss: 0.5139
Epoch 70/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7338 - loss: 0.5158
Epoch 71/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7222 - loss: 0.5574
Epoch 72/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.7534 - loss: 0.5501
Epoch 73/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.7964 - loss: 0.5192
Epoch 74/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.7691 - loss: 0.5398
Epoch 75/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.8199 - loss: 0.5204
Epoch 76/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7691 - loss: 0.5604
Epoch 77/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.8023 - loss: 0.5430
Epoch 78/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7789 - loss: 0.5378
Epoch 79/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7945 - loss: 0.5270
Epoch 80/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7710 - loss: 0.5510
Epoch 81/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7847 - loss: 0.5089
Epoch 82/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7632 - loss: 0.5460
Epoch 83/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.7945 - loss: 0.5459
Epoch 84/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7789 - loss: 0.5468
Epoch 85/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.8141 - loss: 0.5191
Epoch 86/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7984 - loss: 0.5509
Epoch 87/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7633 - loss: 0.5571
Epoch 88/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.7828 - loss: 0.5436
Epoch 89/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7789 - loss: 0.5642
Epoch 90/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.7594 - loss: 0.5625
Epoch 91/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - BinaryAccuracy: 0.8023 - loss: 0.5158
Epoch 92/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - BinaryAccuracy: 0.7789 - loss: 0.5438
Epoch 93/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.8062 - loss: 0.5051
Epoch 94/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.8023 - loss: 0.5265
Epoch 95/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7867 - loss: 0.5090
Epoch 96/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7730 - loss: 0.5109
Epoch 97/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7847 - loss: 0.5101
Epoch 98/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.8102 - loss: 0.4995
Epoch 99/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.7867 - loss: 0.5251
Epoch 100/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7672 - loss: 0.5470
Epoch 101/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7691 - loss: 0.5145
Epoch 102/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7906 - loss: 0.5028
Epoch 103/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.8141 - loss: 0.5022
Epoch 104/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8043 - loss: 0.4874
Epoch 105/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.7398 - loss: 0.5643
Epoch 106/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - BinaryAccuracy: 0.7574 - loss: 0.5001
Epoch 107/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.7671 - loss: 0.5148
Epoch 108/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7750 - loss: 0.4959
Epoch 109/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7828 - loss: 0.4816
Epoch 110/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7378 - loss: 0.5098
Epoch 111/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7632 - loss: 0.5220
Epoch 112/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7906 - loss: 0.4853
Epoch 113/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7554 - loss: 0.5084
Epoch 114/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7984 - loss: 0.4894
Epoch 115/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7710 - loss: 0.4969
Epoch 116/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7554 - loss: 0.5044
Epoch 117/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.8179 - loss: 0.4690
Epoch 118/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7554 - loss: 0.5020
Epoch 119/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7906 - loss: 0.4750
Epoch 120/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7945 - loss: 0.4603
Epoch 121/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - BinaryAccuracy: 0.7789 - loss: 0.4996
Epoch 122/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7710 - loss: 0.4776
Epoch 123/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.7789 - loss: 0.4841
Epoch 124/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7593 - loss: 0.5068
Epoch 125/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7984 - loss: 0.4440
Epoch 126/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7554 - loss: 0.5018
Epoch 127/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7789 - loss: 0.4716
Epoch 128/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7828 - loss: 0.4857
Epoch 129/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7965 - loss: 0.4661
Epoch 130/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.7593 - loss: 0.4893
Epoch 131/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8023 - loss: 0.4914
Epoch 132/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.7828 - loss: 0.4935
Epoch 133/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.7437 - loss: 0.4932
Epoch 134/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - BinaryAccuracy: 0.7710 - loss: 0.4798
Epoch 135/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.7789 - loss: 0.4646
Epoch 136/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - BinaryAccuracy: 0.7554 - loss: 0.4859
Epoch 137/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - BinaryAccuracy: 0.7847 - loss: 0.4730
Epoch 138/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8062 - loss: 0.4505
Epoch 139/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - BinaryAccuracy: 0.7945 - loss: 0.4761
Epoch 140/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - BinaryAccuracy: 0.7984 - loss: 0.4625
Epoch 141/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.7730 - loss: 0.4628
Epoch 142/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8004 - loss: 0.4680
Epoch 143/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.7847 - loss: 0.4556
Epoch 144/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - BinaryAccuracy: 0.7984 - loss: 0.4603
Epoch 145/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - BinaryAccuracy: 0.7906 - loss: 0.4511
Epoch 146/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8180 - loss: 0.4366
Epoch 147/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.7926 - loss: 0.4743
Epoch 148/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8649 - loss: 0.4102
Epoch 149/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8141 - loss: 0.4557
Epoch 150/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - BinaryAccuracy: 0.8258 - loss: 0.4481
Epoch 151/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - BinaryAccuracy: 0.8668 - loss: 0.3966
Epoch 152/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - BinaryAccuracy: 0.8356 - loss: 0.4422
Epoch 153/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - BinaryAccuracy: 0.8200 - loss: 0.4419
Epoch 154/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - BinaryAccuracy: 0.8649 - loss: 0.4121
Epoch 155/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8571 - loss: 0.4162
Epoch 156/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - BinaryAccuracy: 0.8219 - loss: 0.4431
Epoch 157/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8688 - loss: 0.3962
Epoch 158/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8298 - loss: 0.4559
Epoch 159/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - BinaryAccuracy: 0.8669 - loss: 0.4159
Epoch 160/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - BinaryAccuracy: 0.8493 - loss: 0.4228
Epoch 161/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.8551 - loss: 0.3864
Epoch 162/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8356 - loss: 0.4278
Epoch 163/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - BinaryAccuracy: 0.8142 - loss: 0.4638
Epoch 164/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - BinaryAccuracy: 0.8493 - loss: 0.4260
Epoch 165/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8356 - loss: 0.4090
Epoch 166/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - BinaryAccuracy: 0.8591 - loss: 0.4177
Epoch 167/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - BinaryAccuracy: 0.8688 - loss: 0.3670
Epoch 168/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - BinaryAccuracy: 0.8610 - loss: 0.3921
Epoch 169/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8356 - loss: 0.4271
Epoch 170/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - BinaryAccuracy: 0.8357 - loss: 0.4509
Epoch 171/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.8747 - loss: 0.4020
Epoch 172/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8454 - loss: 0.3773
Epoch 173/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8454 - loss: 0.3972
Epoch 174/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8611 - loss: 0.4133
Epoch 175/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.8689 - loss: 0.3987
Epoch 176/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8454 - loss: 0.3877
Epoch 177/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.8747 - loss: 0.3637
Epoch 178/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8747 - loss: 0.3741
Epoch 179/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8728 - loss: 0.3869
Epoch 180/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8376 - loss: 0.4410
Epoch 181/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - BinaryAccuracy: 0.8572 - loss: 0.4007
Epoch 182/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - BinaryAccuracy: 0.8219 - loss: 0.3965
Epoch 183/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8043 - loss: 0.4143
Epoch 184/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - BinaryAccuracy: 0.8493 - loss: 0.3780
Epoch 185/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - BinaryAccuracy: 0.8631 - loss: 0.4241
Epoch 186/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8610 - loss: 0.3893
Epoch 187/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8376 - loss: 0.3955
Epoch 188/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - BinaryAccuracy: 0.8298 - loss: 0.3857
Epoch 189/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - BinaryAccuracy: 0.8415 - loss: 0.3522
Epoch 190/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8571 - loss: 0.3334
Epoch 191/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8708 - loss: 0.3622
Epoch 192/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8728 - loss: 0.3617
Epoch 193/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - BinaryAccuracy: 0.8688 - loss: 0.3657
Epoch 194/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8102 - loss: 0.3947
Epoch 195/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8611 - loss: 0.3609
Epoch 196/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - BinaryAccuracy: 0.8689 - loss: 0.3781
Epoch 197/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8747 - loss: 0.3652
Epoch 198/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8219 - loss: 0.3727
Epoch 199/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8512 - loss: 0.3387
Epoch 200/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - BinaryAccuracy: 0.8649 - loss: 0.3519
Epoch 201/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - BinaryAccuracy: 0.8572 - loss: 0.3773
Epoch 202/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - BinaryAccuracy: 0.8728 - loss: 0.3626
Epoch 203/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8551 - loss: 0.3342
Epoch 204/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8473 - loss: 0.3191
Epoch 205/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8591 - loss: 0.3415
Epoch 206/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8884 - loss: 0.3489
Epoch 207/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8572 - loss: 0.3602
Epoch 208/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - BinaryAccuracy: 0.8395 - loss: 0.3529
Epoch 209/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - BinaryAccuracy: 0.8473 - loss: 0.3403
Epoch 210/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - BinaryAccuracy: 0.8669 - loss: 0.3468
Epoch 211/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8689 - loss: 0.3563
Epoch 212/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - BinaryAccuracy: 0.8708 - loss: 0.3321
Epoch 213/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8884 - loss: 0.3147
Epoch 214/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - BinaryAccuracy: 0.8727 - loss: 0.3096
Epoch 215/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - BinaryAccuracy: 0.8572 - loss: 0.3731
Epoch 216/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - BinaryAccuracy: 0.8767 - loss: 0.3294
Epoch 217/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8513 - loss: 0.3585
Epoch 218/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - BinaryAccuracy: 0.8806 - loss: 0.3137
Epoch 219/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - BinaryAccuracy: 0.8494 - loss: 0.3564
Epoch 220/500

In [23]:
y_pred = model.predict(X_test)
y_pred.shape

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

(43, 1)

In [24]:
# y_pred

In [25]:
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
y_bi_pred.shape

(43,)

In [26]:
# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.7906976744186046
Confusion Matrix:
 [[22  3]
 [ 6 12]]
Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.88      0.83        25
           1       0.80      0.67      0.73        18

    accuracy                           0.79        43
   macro avg       0.79      0.77      0.78        43
weighted avg       0.79      0.79      0.79        43

In [27]:
# Multi Class classification :
df.head()

   Price  SqFt  Bedrooms  Bathrooms  Offers  Brick  Neighborhood
0   0.32  0.30         2          2       2      0             0
1   0.32  0.51         4          2       3      0             0
2   0.32  0.25         3          2       1      0             0
3   0.18  0.46         3          2       3      0             0
4   0.36  0.60         3          3       3      0             0

In [28]:
# Train-Test Split :
X = df.drop('Neighborhood',axis=1)
y = df['Neighborhood']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=43)

print("X_train shape : ",X_train.shape)
print("X_test shape : ",X_test.shape)
print("y_train shape : ",y_train.shape)
print("y_test shape : ",y_test.shape)

X_train shape :  (85, 6)
X_test shape :  (43, 6)
y_train shape :  (85,)
y_test shape :  (43,)

In [29]:
y_train.unique()

array([2, 0, 1])

In [30]:
y_test.unique()

array([0, 2, 1])

In [31]:
# Assuming train_y contains class labels like [0, 1, 2, 3, 4]
num_classes = len(set(y_train))  # Automatically detect number of classes

# One-Hot Encode the Labels
train_y = to_categorical(y_train, num_classes)

# Build the MLP Model
model = tf.keras.Sequential()

# Model : 
model.add(tf.keras.layers.Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

# Compile the Model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the Model
history = model.fit(X_train, train_y, epochs=500)

# Predict the Output
y_pred = model.predict(X_test)

# Convert Softmax Probabilities to Class Labels
y_pred_classes = y_pred.argmax(axis=1)

Epoch 1/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.2876 - loss: 1.2240
Epoch 2/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3268 - loss: 1.1108
Epoch 3/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5401 - loss: 1.0656
Epoch 4/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5499 - loss: 1.0435
Epoch 5/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5284 - loss: 1.0435
Epoch 6/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5675 - loss: 1.0139
Epoch 7/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6203 - loss: 1.0040
Epoch 8/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5871 - loss: 0.9988
Epoch 9/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6067 - loss: 0.9827
Epoch 10/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6067 - loss: 0.9541
Epoch 11/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6321 - loss: 0.9297
Epoch 12/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6555 - loss: 0.8865
Epoch 13/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6223 - loss: 0.8843
Epoch 14/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6223 - loss: 0.8642
Epoch 15/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6204 - loss: 0.8681
Epoch 16/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6457 - loss: 0.8318
Epoch 17/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6438 - loss: 0.8066
Epoch 18/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6301 - loss: 0.8355
Epoch 19/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6672 - loss: 0.7772
Epoch 20/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6262 - loss: 0.7868
Epoch 21/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6243 - loss: 0.8082
Epoch 22/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6536 - loss: 0.7860
Epoch 23/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6399 - loss: 0.7985
Epoch 24/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6223 - loss: 0.7965
Epoch 25/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6204 - loss: 0.7703
Epoch 26/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6790 - loss: 0.7236
Epoch 27/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6458 - loss: 0.7362
Epoch 28/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6517 - loss: 0.7685
Epoch 29/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6575 - loss: 0.7344
Epoch 30/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6086 - loss: 0.7253
Epoch 31/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6946 - loss: 0.6943
Epoch 32/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6341 - loss: 0.7531
Epoch 33/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6634 - loss: 0.7205
Epoch 34/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6341 - loss: 0.7352
Epoch 35/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6575 - loss: 0.7081
Epoch 36/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6282 - loss: 0.7397
Epoch 37/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6653 - loss: 0.7079
Epoch 38/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6458 - loss: 0.7169
Epoch 39/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6458 - loss: 0.7355
Epoch 40/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6087 - loss: 0.7451
Epoch 41/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6517 - loss: 0.6846
Epoch 42/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6693 - loss: 0.6830
Epoch 43/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6498 - loss: 0.7230
Epoch 44/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6966 - loss: 0.6700
Epoch 45/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6537 - loss: 0.7157
Epoch 46/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6380 - loss: 0.7107
Epoch 47/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6634 - loss: 0.6838
Epoch 48/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6849 - loss: 0.6777
Epoch 49/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6830 - loss: 0.6753
Epoch 50/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6986 - loss: 0.6719
Epoch 51/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6674 - loss: 0.6907
Epoch 52/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6674 - loss: 0.6954
Epoch 53/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6732 - loss: 0.6917
Epoch 54/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6673 - loss: 0.6544
Epoch 55/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6791 - loss: 0.6558
Epoch 56/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7162 - loss: 0.6156
Epoch 57/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7025 - loss: 0.6402
Epoch 58/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6966 - loss: 0.6362
Epoch 59/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7103 - loss: 0.6163
Epoch 60/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6713 - loss: 0.6624
Epoch 61/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6987 - loss: 0.6668
Epoch 62/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7377 - loss: 0.6127
Epoch 63/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6966 - loss: 0.6185
Epoch 64/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7397 - loss: 0.6059
Epoch 65/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6790 - loss: 0.6003
Epoch 66/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7397 - loss: 0.6198
Epoch 67/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7221 - loss: 0.6299
Epoch 68/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6948 - loss: 0.6510
Epoch 69/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7084 - loss: 0.6176
Epoch 70/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7065 - loss: 0.6114
Epoch 71/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7045 - loss: 0.6080
Epoch 72/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7455 - loss: 0.5692
Epoch 73/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6909 - loss: 0.6316
Epoch 74/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7260 - loss: 0.5692
Epoch 75/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7202 - loss: 0.5949
Epoch 76/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7690 - loss: 0.5437
Epoch 77/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7417 - loss: 0.5851
Epoch 78/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7300 - loss: 0.5791
Epoch 79/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6909 - loss: 0.6200
Epoch 80/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7475 - loss: 0.5700
Epoch 81/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7339 - loss: 0.5819
Epoch 82/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7338 - loss: 0.5384
Epoch 83/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7222 - loss: 0.5722
Epoch 84/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7495 - loss: 0.5362
Epoch 85/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7378 - loss: 0.5566
Epoch 86/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7319 - loss: 0.5550
Epoch 87/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7299 - loss: 0.5454
Epoch 88/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7730 - loss: 0.5278
Epoch 89/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7886 - loss: 0.5039
Epoch 90/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7300 - loss: 0.5638
Epoch 91/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7730 - loss: 0.4992
Epoch 92/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8023 - loss: 0.5009
Epoch 93/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7495 - loss: 0.5599
Epoch 94/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7847 - loss: 0.5019
Epoch 95/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7632 - loss: 0.5173
Epoch 96/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7984 - loss: 0.5078
Epoch 97/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7847 - loss: 0.4935
Epoch 98/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8081 - loss: 0.4704
Epoch 99/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7437 - loss: 0.5214
Epoch 100/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.4755
Epoch 101/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7750 - loss: 0.4928
Epoch 102/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7750 - loss: 0.5042
Epoch 103/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7671 - loss: 0.5077
Epoch 104/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7886 - loss: 0.4752
Epoch 105/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8375 - loss: 0.4766
Epoch 106/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7672 - loss: 0.5102
Epoch 107/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8141 - loss: 0.4829
Epoch 108/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8160 - loss: 0.4637
Epoch 109/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8219 - loss: 0.4440
Epoch 110/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7945 - loss: 0.4809
Epoch 111/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7886 - loss: 0.4934
Epoch 112/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7711 - loss: 0.5153
Epoch 113/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8062 - loss: 0.4286
Epoch 114/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7653 - loss: 0.5069
Epoch 115/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7828 - loss: 0.4762
Epoch 116/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7945 - loss: 0.4566
Epoch 117/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8082 - loss: 0.4580
Epoch 118/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8532 - loss: 0.4334
Epoch 119/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8551 - loss: 0.4476
Epoch 120/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8434 - loss: 0.4342
Epoch 121/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8239 - loss: 0.4415
Epoch 122/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8630 - loss: 0.4308
Epoch 123/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8102 - loss: 0.4385
Epoch 124/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8473 - loss: 0.4415
Epoch 125/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8473 - loss: 0.4362
Epoch 126/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8043 - loss: 0.4508
Epoch 127/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8552 - loss: 0.4447
Epoch 128/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8454 - loss: 0.4033
Epoch 129/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8239 - loss: 0.4365
Epoch 130/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9021 - loss: 0.4067
Epoch 131/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8689 - loss: 0.3962
Epoch 132/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8747 - loss: 0.3675
Epoch 133/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8376 - loss: 0.3978
Epoch 134/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8649 - loss: 0.4026
Epoch 135/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8513 - loss: 0.4061
Epoch 136/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8845 - loss: 0.3812
Epoch 137/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8728 - loss: 0.4076
Epoch 138/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8884 - loss: 0.4088
Epoch 139/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8415 - loss: 0.4381
Epoch 140/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8454 - loss: 0.3976
Epoch 141/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8669 - loss: 0.3707
Epoch 142/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8787 - loss: 0.4017
Epoch 143/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8708 - loss: 0.3803
Epoch 144/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8708 - loss: 0.3671
Epoch 145/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8786 - loss: 0.3716
Epoch 146/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8904 - loss: 0.3749
Epoch 147/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8513 - loss: 0.3642
Epoch 148/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8689 - loss: 0.3970
Epoch 149/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9021 - loss: 0.3416
Epoch 150/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8845 - loss: 0.3631
Epoch 151/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8903 - loss: 0.3505
Epoch 152/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8454 - loss: 0.3659
Epoch 153/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8591 - loss: 0.3668
Epoch 154/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8826 - loss: 0.3498
Epoch 155/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8688 - loss: 0.3701
Epoch 156/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9022 - loss: 0.3577
Epoch 157/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8513 - loss: 0.3745
Epoch 158/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8728 - loss: 0.3597
Epoch 159/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9139 - loss: 0.3234
Epoch 160/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8963 - loss: 0.3597
Epoch 161/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8826 - loss: 0.3600
Epoch 162/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9256 - loss: 0.3434
Epoch 163/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8513 - loss: 0.3738
Epoch 164/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8865 - loss: 0.3522
Epoch 165/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9178 - loss: 0.3292
Epoch 166/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8631 - loss: 0.3430
Epoch 167/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8825 - loss: 0.3410
Epoch 168/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9060 - loss: 0.3215
Epoch 169/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8963 - loss: 0.3363
Epoch 170/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9236 - loss: 0.3090
Epoch 171/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9256 - loss: 0.3276
Epoch 172/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8533 - loss: 0.3936
Epoch 173/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.9217 - loss: 0.3108
Epoch 174/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8806 - loss: 0.3575
Epoch 175/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8552 - loss: 0.3762
Epoch 176/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8924 - loss: 0.3316
Epoch 177/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8943 - loss: 0.3683
Epoch 178/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8846 - loss: 0.3429
Epoch 179/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9236 - loss: 0.2939
Epoch 180/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8807 - loss: 0.3587
Epoch 181/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8728 - loss: 0.3393
Epoch 182/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9041 - loss: 0.3301
Epoch 183/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8825 - loss: 0.3346
Epoch 184/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9060 - loss: 0.3077
Epoch 185/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8396 - loss: 0.4010
Epoch 186/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8787 - loss: 0.3435
Epoch 187/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8787 - loss: 0.3370
Epoch 188/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8943 - loss: 0.3084
Epoch 189/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8924 - loss: 0.3231
Epoch 190/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8708 - loss: 0.3407
Epoch 191/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9041 - loss: 0.2851
Epoch 192/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8552 - loss: 0.3244
Epoch 193/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9002 - loss: 0.2831
Epoch 194/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9217 - loss: 0.2862
Epoch 195/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8904 - loss: 0.3245
Epoch 196/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8591 - loss: 0.3473
Epoch 197/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9256 - loss: 0.2745
Epoch 198/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8669 - loss: 0.2996
Epoch 199/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9119 - loss: 0.2982
Epoch 200/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8786 - loss: 0.3045
Epoch 201/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8708 - loss: 0.2734
Epoch 202/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8767 - loss: 0.3053
Epoch 203/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8650 - loss: 0.3243
Epoch 204/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8826 - loss: 0.3159
Epoch 205/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8963 - loss: 0.2945
Epoch 206/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8885 - loss: 0.2877
Epoch 207/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8748 - loss: 0.2927
Epoch 208/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8924 - loss: 0.2927
Epoch 209/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8767 - loss: 0.3045
Epoch 210/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9100 - loss: 0.2961
Epoch 211/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8787 - loss: 0.3143
Epoch 212/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9100 - loss: 0.2832
Epoch 213/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9061 - loss: 0.3054
Epoch 214/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8572 - loss: 0.3131
Epoch 215/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9100 - loss: 0.2694
Epoch 216/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9002 - loss: 0.2604
Epoch 217/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9159 - loss: 0.2805
Epoch 218/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8591 - loss: 0.3029
Epoch 219/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8865 - loss: 0.2780
Epoch 220/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8689 - loss: 0.3120
Epoch 221/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8649 - loss: 0.3136
Epoch 222/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 507us/step - accuracy: 0.9217 - loss: 0.2682
Epoch 223/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8376 - loss: 0.3005
Epoch 224/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8728 - loss: 0.2987
Epoch 225/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9139 - loss: 0.2535
Epoch 226/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8807 - loss: 0.2943
Epoch 227/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8865 - loss: 0.3033
Epoch 228/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8982 - loss: 0.2623
Epoch 229/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9061 - loss: 0.2658
Epoch 230/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9002 - loss: 0.2702
Epoch 231/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9159 - loss: 0.2641
Epoch 232/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8963 - loss: 0.2590
Epoch 233/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9061 - loss: 0.2439
Epoch 234/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8943 - loss: 0.2612
Epoch 235/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9080 - loss: 0.2611
Epoch 236/500

In [32]:
# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_pred_classes)
conf_matrix = confusion_matrix(y_test, y_pred_classes)
class_report = classification_report(y_test, y_pred_classes)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.6511627906976745
Confusion Matrix:
 [[10  9  3]
 [ 3  9  0]
 [ 0  0  9]]
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.45      0.57        22
           1       0.50      0.75      0.60        12
           2       0.75      1.00      0.86         9

    accuracy                           0.65        43
   macro avg       0.67      0.73      0.68        43
weighted avg       0.69      0.65      0.64        43