## Lab 04 - ANN DL - Optimizers effect on Classification Model

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.datasets import make_regression
from sklearn import metrics
from sklearn import decomposition
from sklearn import manifold
from tqdm.notebook import trange, tqdm

#TensorFlow and Keras Libraries
import tensorflow as tf
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model
import torch
from torchvision import transforms
from tensorflow.keras.utils import to_categorical
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data
import torchvision
import torchvision.datasets as datasets
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os

# Hiding the warnings
import warnings
warnings.filterwarnings('ignore')

# Extra Libraries
import copy
import random
import time

In [2]:
data_path = "DataBase/Class_Data/house-prices.csv"
df = pd.read_csv(data_path)

In [3]:
df.head()

   Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300  1790         2          2       2    No         East
1     2  114200  2030         4          2       3    No         East
2     3  114800  1740         3          2       1    No         East
3     4   94700  1980         3          2       3    No         East
4     5  119800  2130         3          3       3    No         East

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Home,128.0,64.500000,37.094474,1.0,32.75,64.5,96.25,128.0
Price,128.0,130427.343750,26868.770371,69100.0,111325.00,125950.0,148250.00,211200.0
SqFt,128.0,2000.937500,211.572431,1450.0,1880.00,2000.0,2140.00,2590.0
Bedrooms,128.0,3.023438,0.725951,2.0,3.00,3.0,3.00,5.0
Bathrooms,128.0,2.445312,0.514492,2.0,2.00,2.0,3.00,4.0
Offers,128.0,2.578125,1.069324,1.0,2.00,3.0,3.00,6.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Home          128 non-null    int64
 1   Price         128 non-null    int64
 2   SqFt          128 non-null    int64
 3   Bedrooms      128 non-null    int64
 4   Bathrooms     128 non-null    int64
 5   Offers        128 non-null    int64
 6   Brick         128 non-null    object
 7   Neighborhood  128 non-null    object
dtypes: int64(6), object(2)
memory usage: 8.1+ KB

In [6]:
df.isna().sum()

Home            0
Price           0
SqFt            0
Bedrooms        0
Bathrooms       0
Offers          0
Brick           0
Neighborhood    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
cat_col = []
for i in df.columns:
    if df[i].dtype == 'O':
        cat_col.append(i)

cat_col

['Brick', 'Neighborhood']

In [9]:
df['Brick'].value_counts()

Brick
No     86
Yes    42
Name: count, dtype: int64

In [10]:
df[cat_col].nunique()

Brick           2
Neighborhood    3
dtype: int64

In [11]:
# Now using Label Encoder :
le1 = LabelEncoder()
df['Brick'] = le1.fit_transform(df['Brick'])
df['Brick'].unique()

le2 = LabelEncoder()
df['Neighborhood'] = le2.fit_transform(df['Neighborhood'])
df['Neighborhood'].unique()

array([0, 1, 2])

In [12]:
# Dropping column - "Home"
df.drop('Home',axis=1,inplace=True)

In [13]:
# Standardization of data :
sc1 = MinMaxScaler()
df[['Price']] = sc1.fit_transform(df[['Price']])

sc2 = MinMaxScaler()
df[['SqFt']] = sc2.fit_transform(df[['SqFt']])

In [14]:
df['Price'] = round(df['Price'],2)
df['SqFt'] = round(df['SqFt'],2)

In [15]:
df.head()

   Price  SqFt  Bedrooms  Bathrooms  Offers  Brick  Neighborhood
0   0.32  0.30         2          2       2      0             0
1   0.32  0.51         4          2       3      0             0
2   0.32  0.25         3          2       1      0             0
3   0.18  0.46         3          2       3      0             0
4   0.36  0.60         3          3       3      0             0

In [16]:
# Binary Class Classification :
X = df.drop('Brick',axis=1)
y = df['Brick']

In [17]:
# Train-Test Split :
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)
print("X_train shape : ",X_train.shape)
print("X_test shape : ",X_test.shape)
print("y_train shape : ",y_train.shape)
print("y_test shape : ",y_test.shape)

X_train shape :  (85, 6)
X_test shape :  (43, 6)
y_train shape :  (85,)
y_test shape :  (43,)

In [18]:
# Building MLP model for Binary Class Classification :
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(45,activation='relu',input_dim = 6))
model.add(tf.keras.layers.Dense(25,activation='relu'))
model.add(tf.keras.layers.Dense(15,activation='relu'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

In [19]:
# 1. We are using adam optimizer :
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adam', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=500)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - BinaryAccuracy: 0.2916 - loss: 0.7442
Epoch 2/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.3150 - loss: 0.7239
Epoch 3/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.3679 - loss: 0.7068
Epoch 4/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.4756 - loss: 0.6898
Epoch 5/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7338 - loss: 0.6708
Epoch 6/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.6909 - loss: 0.6539
Epoch 7/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.6987 - loss: 0.6452
Epoch 8/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7065 - loss: 0.6174
Epoch 9/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7377 - loss: 0.5932
Epoch 10/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7416 - loss: 0.5873
Epoch 11/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7065 - loss: 0.6115
Epoch 12/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7104 - loss: 0.6067
Epoch 13/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7026 - loss: 0.6225
Epoch 14/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.6909 - loss: 0.6228
Epoch 15/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7338 - loss: 0.5823
Epoch 16/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7221 - loss: 0.5894
Epoch 17/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.6830 - loss: 0.6202
Epoch 18/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.6987 - loss: 0.5988
Epoch 19/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7338 - loss: 0.5745
Epoch 20/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7260 - loss: 0.5763
Epoch 21/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7026 - loss: 0.5944
Epoch 22/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7299 - loss: 0.5694
Epoch 23/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7143 - loss: 0.5798
Epoch 24/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7534 - loss: 0.5403
Epoch 25/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7182 - loss: 0.5722
Epoch 26/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7455 - loss: 0.5460
Epoch 27/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.6987 - loss: 0.5855
Epoch 28/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7612 - loss: 0.5374
Epoch 29/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.7260 - loss: 0.5605
Epoch 30/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7026 - loss: 0.5806
Epoch 31/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7338 - loss: 0.5442
Epoch 32/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7143 - loss: 0.5611
Epoch 33/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7377 - loss: 0.5509
Epoch 34/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7026 - loss: 0.5701
Epoch 35/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7416 - loss: 0.5327
Epoch 36/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7299 - loss: 0.5368
Epoch 37/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.6987 - loss: 0.5733
Epoch 38/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7260 - loss: 0.5454
Epoch 39/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7104 - loss: 0.5483
Epoch 40/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7026 - loss: 0.5538
Epoch 41/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7377 - loss: 0.5330
Epoch 42/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7104 - loss: 0.5581
Epoch 43/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7299 - loss: 0.5407
Epoch 44/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7065 - loss: 0.5561
Epoch 45/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7085 - loss: 0.5517
Epoch 46/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7163 - loss: 0.5499
Epoch 47/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7436 - loss: 0.5153
Epoch 48/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7514 - loss: 0.5210
Epoch 49/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7202 - loss: 0.5534
Epoch 50/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7475 - loss: 0.5195
Epoch 51/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7592 - loss: 0.5096
Epoch 52/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7456 - loss: 0.5472
Epoch 53/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7515 - loss: 0.5288
Epoch 54/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7768 - loss: 0.4992
Epoch 55/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7515 - loss: 0.5232
Epoch 56/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7632 - loss: 0.5413
Epoch 57/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7710 - loss: 0.5071
Epoch 58/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7222 - loss: 0.5731
Epoch 59/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8120 - loss: 0.4814
Epoch 60/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7495 - loss: 0.5253
Epoch 61/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7456 - loss: 0.5390
Epoch 62/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7808 - loss: 0.4997
Epoch 63/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.7847 - loss: 0.5196
Epoch 64/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7613 - loss: 0.5309
Epoch 65/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7613 - loss: 0.5298
Epoch 66/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7652 - loss: 0.5144
Epoch 67/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7417 - loss: 0.5200
Epoch 68/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7671 - loss: 0.4988
Epoch 69/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7632 - loss: 0.4920
Epoch 70/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7612 - loss: 0.5074
Epoch 71/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7613 - loss: 0.5121
Epoch 72/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7769 - loss: 0.5177
Epoch 73/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7593 - loss: 0.5271
Epoch 74/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7828 - loss: 0.5087
Epoch 75/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.7574 - loss: 0.5238
Epoch 76/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7378 - loss: 0.5288
Epoch 77/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7905 - loss: 0.4797
Epoch 78/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.7378 - loss: 0.5247
Epoch 79/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7828 - loss: 0.4924
Epoch 80/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7554 - loss: 0.5167
Epoch 81/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7359 - loss: 0.5327
Epoch 82/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7378 - loss: 0.5059
Epoch 83/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7437 - loss: 0.5358
Epoch 84/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7789 - loss: 0.4819
Epoch 85/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7808 - loss: 0.4970
Epoch 86/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7652 - loss: 0.4751
Epoch 87/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7378 - loss: 0.4986
Epoch 88/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8062 - loss: 0.4588
Epoch 89/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7671 - loss: 0.5068
Epoch 90/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7359 - loss: 0.5006
Epoch 91/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7613 - loss: 0.4660
Epoch 92/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7730 - loss: 0.4407
Epoch 93/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7593 - loss: 0.4699
Epoch 94/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8278 - loss: 0.4782
Epoch 95/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8199 - loss: 0.4651
Epoch 96/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8180 - loss: 0.4687
Epoch 97/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7671 - loss: 0.4968
Epoch 98/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7769 - loss: 0.4693
Epoch 99/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7984 - loss: 0.4419
Epoch 100/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8141 - loss: 0.4497
Epoch 101/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8004 - loss: 0.4594
Epoch 102/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8238 - loss: 0.4344
Epoch 103/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8102 - loss: 0.4522
Epoch 104/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8141 - loss: 0.4388
Epoch 105/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8043 - loss: 0.4550
Epoch 106/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8219 - loss: 0.4267
Epoch 107/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.7984 - loss: 0.4681
Epoch 108/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8141 - loss: 0.4677
Epoch 109/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8043 - loss: 0.4626
Epoch 110/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8043 - loss: 0.4600
Epoch 111/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8375 - loss: 0.4297
Epoch 112/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8336 - loss: 0.4322
Epoch 113/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8336 - loss: 0.4139
Epoch 114/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8336 - loss: 0.4110
Epoch 115/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8102 - loss: 0.4506
Epoch 116/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8278 - loss: 0.4410
Epoch 117/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8317 - loss: 0.4136
Epoch 118/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8336 - loss: 0.4397
Epoch 119/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8219 - loss: 0.4215
Epoch 120/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8219 - loss: 0.4365
Epoch 121/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8375 - loss: 0.3945
Epoch 122/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8180 - loss: 0.4323
Epoch 123/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8102 - loss: 0.4512
Epoch 124/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8395 - loss: 0.4071
Epoch 125/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8395 - loss: 0.4080
Epoch 126/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8434 - loss: 0.4043
Epoch 127/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8219 - loss: 0.4185
Epoch 128/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8161 - loss: 0.4493
Epoch 129/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8669 - loss: 0.4013
Epoch 130/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8356 - loss: 0.4189
Epoch 131/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.7926 - loss: 0.4444
Epoch 132/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8649 - loss: 0.3943
Epoch 133/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8278 - loss: 0.4088
Epoch 134/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.8317 - loss: 0.4149
Epoch 135/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8278 - loss: 0.4014
Epoch 136/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8258 - loss: 0.3920
Epoch 137/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8278 - loss: 0.4185
Epoch 138/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8239 - loss: 0.3988
Epoch 139/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8649 - loss: 0.3860
Epoch 140/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8239 - loss: 0.4126
Epoch 141/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8571 - loss: 0.3758
Epoch 142/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8512 - loss: 0.3840
Epoch 143/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8786 - loss: 0.3682
Epoch 144/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8903 - loss: 0.3726
Epoch 145/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8825 - loss: 0.3614
Epoch 146/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8278 - loss: 0.3910
Epoch 147/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.8434 - loss: 0.3975
Epoch 148/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8591 - loss: 0.3468
Epoch 149/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8552 - loss: 0.3889
Epoch 150/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.8767 - loss: 0.3741
Epoch 151/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8591 - loss: 0.3736
Epoch 152/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8083 - loss: 0.4141
Epoch 153/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8513 - loss: 0.3709
Epoch 154/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8864 - loss: 0.3434
Epoch 155/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8630 - loss: 0.3748
Epoch 156/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8669 - loss: 0.3654
Epoch 157/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8650 - loss: 0.3896
Epoch 158/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8552 - loss: 0.3679
Epoch 159/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8943 - loss: 0.3658
Epoch 160/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8650 - loss: 0.3396
Epoch 161/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8728 - loss: 0.3591
Epoch 162/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8669 - loss: 0.3660
Epoch 163/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8611 - loss: 0.3656
Epoch 164/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8630 - loss: 0.3467
Epoch 165/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8845 - loss: 0.3211
Epoch 166/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8455 - loss: 0.3894
Epoch 167/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8884 - loss: 0.3221
Epoch 168/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8435 - loss: 0.3581
Epoch 169/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8727 - loss: 0.3260
Epoch 170/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8610 - loss: 0.3120
Epoch 171/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8572 - loss: 0.3630
Epoch 172/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8787 - loss: 0.3581
Epoch 173/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8669 - loss: 0.3349
Epoch 174/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8650 - loss: 0.3345
Epoch 175/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8826 - loss: 0.3408
Epoch 176/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8826 - loss: 0.3512
Epoch 177/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8806 - loss: 0.3351
Epoch 178/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8415 - loss: 0.3252
Epoch 179/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8533 - loss: 0.3434
Epoch 180/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9001 - loss: 0.3043
Epoch 181/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8650 - loss: 0.3202
Epoch 182/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8709 - loss: 0.3340
Epoch 183/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8806 - loss: 0.3022
Epoch 184/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.8455 - loss: 0.3443
Epoch 185/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8982 - loss: 0.2895
Epoch 186/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8728 - loss: 0.3048
Epoch 187/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8728 - loss: 0.3125
Epoch 188/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8650 - loss: 0.3089
Epoch 189/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8631 - loss: 0.3417
Epoch 190/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8865 - loss: 0.3108
Epoch 191/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8787 - loss: 0.2873
Epoch 192/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8924 - loss: 0.3010
Epoch 193/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.8826 - loss: 0.2902
Epoch 194/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8670 - loss: 0.3006
Epoch 195/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8376 - loss: 0.3264
Epoch 196/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.8572 - loss: 0.3072
Epoch 197/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8943 - loss: 0.2925
Epoch 198/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8924 - loss: 0.2973
Epoch 199/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9334 - loss: 0.2586
Epoch 200/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8787 - loss: 0.3068
Epoch 201/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9061 - loss: 0.2728
Epoch 202/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9393 - loss: 0.2570
Epoch 203/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.8963 - loss: 0.2897
Epoch 204/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8845 - loss: 0.2878
Epoch 205/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9100 - loss: 0.2943
Epoch 206/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9080 - loss: 0.2895
Epoch 207/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9178 - loss: 0.2729
Epoch 208/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.8709 - loss: 0.2931
Epoch 209/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8533 - loss: 0.3248
Epoch 210/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9139 - loss: 0.2851
Epoch 211/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9080 - loss: 0.2633
Epoch 212/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8650 - loss: 0.3086
Epoch 213/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9178 - loss: 0.2633
Epoch 214/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9061 - loss: 0.3001
Epoch 215/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8924 - loss: 0.2757
Epoch 216/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9139 - loss: 0.2547
Epoch 217/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9080 - loss: 0.2796
Epoch 218/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8924 - loss: 0.2735
Epoch 219/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.8983 - loss: 0.2880
Epoch 220/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9119 - loss: 0.2797
Epoch 221/500

In [20]:
start_test = time.time()
test_loss, test_acc = model.evaluate(X_test, y_test)
end_test = time.time()
testing_time = end_test - start_test
print(f"Testing time: {testing_time:.2f} seconds")

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.7357 - loss: 0.6430
Testing time: 0.14 seconds

In [21]:
y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
(43, 1)
(43,)

In [22]:
# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.7441860465116279
Confusion Matrix:
 [[20  5]
 [ 6 12]]
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.80      0.78        25
           1       0.71      0.67      0.69        18

    accuracy                           0.74        43
   macro avg       0.74      0.73      0.74        43
weighted avg       0.74      0.74      0.74        43

In [23]:
# 2. We are using rmsprop optimizer :
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='rmsprop', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=500)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - BinaryAccuracy: 0.8747 - loss: 0.3351
Epoch 2/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9374 - loss: 0.1210
Epoch 3/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9530 - loss: 0.1019
Epoch 4/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9354 - loss: 0.1067
Epoch 5/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9511 - loss: 0.1008
Epoch 6/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9569 - loss: 0.1175
Epoch 7/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9628 - loss: 0.1191
Epoch 8/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.9511 - loss: 0.0927
Epoch 9/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9628 - loss: 0.1114
Epoch 10/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9393 - loss: 0.1014
Epoch 11/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9198 - loss: 0.1831
Epoch 12/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.8846 - loss: 0.1720
Epoch 13/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9374 - loss: 0.1161
Epoch 14/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9296 - loss: 0.1199
Epoch 15/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9491 - loss: 0.0854
Epoch 16/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9726 - loss: 0.0848
Epoch 17/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9452 - loss: 0.1196
Epoch 18/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9393 - loss: 0.0994
Epoch 19/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9452 - loss: 0.1141
Epoch 20/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9530 - loss: 0.1129
Epoch 21/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.8631 - loss: 0.2269
Epoch 22/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.9374 - loss: 0.1188
Epoch 23/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9608 - loss: 0.1001
Epoch 24/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9569 - loss: 0.0992
Epoch 25/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9452 - loss: 0.1168
Epoch 26/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9608 - loss: 0.0869
Epoch 27/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9295 - loss: 0.1380
Epoch 28/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9472 - loss: 0.1510
Epoch 29/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9569 - loss: 0.1359
Epoch 30/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - BinaryAccuracy: 0.9667 - loss: 0.1026
Epoch 31/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.9530 - loss: 0.1034
Epoch 32/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9608 - loss: 0.0977
Epoch 33/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9569 - loss: 0.0934
Epoch 34/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9511 - loss: 0.1027
Epoch 35/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9276 - loss: 0.1824
Epoch 36/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9491 - loss: 0.1032
Epoch 37/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9354 - loss: 0.1084
Epoch 38/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.9550 - loss: 0.1379
Epoch 39/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9569 - loss: 0.0944
Epoch 40/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9589 - loss: 0.0826
Epoch 41/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9217 - loss: 0.1479
Epoch 42/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9413 - loss: 0.1232
Epoch 43/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9511 - loss: 0.0862
Epoch 44/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9608 - loss: 0.1034
Epoch 45/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9178 - loss: 0.1533
Epoch 46/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9472 - loss: 0.0978
Epoch 47/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9021 - loss: 0.1518
Epoch 48/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9667 - loss: 0.1103
Epoch 49/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9530 - loss: 0.0963
Epoch 50/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9276 - loss: 0.1281
Epoch 51/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9472 - loss: 0.1105
Epoch 52/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9569 - loss: 0.0930
Epoch 53/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9569 - loss: 0.1070
Epoch 54/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9374 - loss: 0.1092
Epoch 55/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9022 - loss: 0.2188
Epoch 56/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9491 - loss: 0.0967
Epoch 57/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9491 - loss: 0.1068
Epoch 58/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9511 - loss: 0.0925
Epoch 59/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9589 - loss: 0.1073
Epoch 60/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - BinaryAccuracy: 0.9608 - loss: 0.1059
Epoch 61/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9569 - loss: 0.1055
Epoch 62/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9745 - loss: 0.0869
Epoch 63/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9608 - loss: 0.0917
Epoch 64/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9589 - loss: 0.1139
Epoch 65/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9276 - loss: 0.1716
Epoch 66/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9628 - loss: 0.0934
Epoch 67/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9608 - loss: 0.0871
Epoch 68/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9706 - loss: 0.0829
Epoch 69/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9608 - loss: 0.1102
Epoch 70/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9511 - loss: 0.0945
Epoch 71/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9374 - loss: 0.1240
Epoch 72/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9452 - loss: 0.0884
Epoch 73/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9432 - loss: 0.1347
Epoch 74/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9452 - loss: 0.1099
Epoch 75/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9413 - loss: 0.1047
Epoch 76/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9374 - loss: 0.1149
Epoch 77/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9550 - loss: 0.1131
Epoch 78/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9374 - loss: 0.0998
Epoch 79/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9452 - loss: 0.1228
Epoch 80/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9726 - loss: 0.0763
Epoch 81/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9472 - loss: 0.1013
Epoch 82/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9648 - loss: 0.0917
Epoch 83/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9589 - loss: 0.1197
Epoch 84/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9452 - loss: 0.1104
Epoch 85/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9589 - loss: 0.0982
Epoch 86/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9295 - loss: 0.0990
Epoch 87/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9472 - loss: 0.1141
Epoch 88/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9569 - loss: 0.0888
Epoch 89/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9608 - loss: 0.1151
Epoch 90/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9354 - loss: 0.1414
Epoch 91/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9550 - loss: 0.1078
Epoch 92/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9687 - loss: 0.0782
Epoch 93/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9335 - loss: 0.1001
Epoch 94/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9315 - loss: 0.1083
Epoch 95/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9119 - loss: 0.1385
Epoch 96/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9628 - loss: 0.0860
Epoch 97/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9706 - loss: 0.0877
Epoch 98/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9491 - loss: 0.0988
Epoch 99/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9432 - loss: 0.0887
Epoch 100/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9139 - loss: 0.1672
Epoch 101/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9550 - loss: 0.1115
Epoch 102/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9608 - loss: 0.0848
Epoch 103/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9745 - loss: 0.0823
Epoch 104/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9550 - loss: 0.1053
Epoch 105/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9765 - loss: 0.0972
Epoch 106/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9550 - loss: 0.1064
Epoch 107/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9589 - loss: 0.0880
Epoch 108/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9452 - loss: 0.1412
Epoch 109/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9784 - loss: 0.0671
Epoch 110/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.8670 - loss: 0.2200
Epoch 111/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9550 - loss: 0.0927
Epoch 112/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9726 - loss: 0.0846
Epoch 113/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9745 - loss: 0.0827
Epoch 114/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.9569 - loss: 0.0861
Epoch 115/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9745 - loss: 0.0734
Epoch 116/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9393 - loss: 0.1085
Epoch 117/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9667 - loss: 0.0955
Epoch 118/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9745 - loss: 0.0848
Epoch 119/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9784 - loss: 0.0740
Epoch 120/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.9217 - loss: 0.1042
Epoch 121/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9589 - loss: 0.0893
Epoch 122/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9511 - loss: 0.0893
Epoch 123/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9256 - loss: 0.1568
Epoch 124/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9530 - loss: 0.0818
Epoch 125/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9726 - loss: 0.1060
Epoch 126/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9550 - loss: 0.1007
Epoch 127/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9608 - loss: 0.0804
Epoch 128/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9589 - loss: 0.1318
Epoch 129/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.9472 - loss: 0.0983
Epoch 130/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9550 - loss: 0.0992
Epoch 131/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9511 - loss: 0.1008
Epoch 132/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9393 - loss: 0.0994
Epoch 133/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.8826 - loss: 0.1895
Epoch 134/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9628 - loss: 0.0813
Epoch 135/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9843 - loss: 0.0766
Epoch 136/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9511 - loss: 0.0997
Epoch 137/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9315 - loss: 0.1217
Epoch 138/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9648 - loss: 0.0934
Epoch 139/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9550 - loss: 0.1044
Epoch 140/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9784 - loss: 0.0770
Epoch 141/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9726 - loss: 0.0988
Epoch 142/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9511 - loss: 0.0788
Epoch 143/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9217 - loss: 0.1821
Epoch 144/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9726 - loss: 0.0879
Epoch 145/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9843 - loss: 0.0701
Epoch 146/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9648 - loss: 0.0951
Epoch 147/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9824 - loss: 0.0914
Epoch 148/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9765 - loss: 0.0892
Epoch 149/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9687 - loss: 0.0909
Epoch 150/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - BinaryAccuracy: 0.9178 - loss: 0.1280
Epoch 151/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.9511 - loss: 0.0976
Epoch 152/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9569 - loss: 0.0880
Epoch 153/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9589 - loss: 0.0894
Epoch 154/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9745 - loss: 0.0743
Epoch 155/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9354 - loss: 0.1508
Epoch 156/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9491 - loss: 0.1305
Epoch 157/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9608 - loss: 0.0771
Epoch 158/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9374 - loss: 0.1084
Epoch 159/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9393 - loss: 0.0926
Epoch 160/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9569 - loss: 0.1057
Epoch 161/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9550 - loss: 0.0900
Epoch 162/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9824 - loss: 0.0881
Epoch 163/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9491 - loss: 0.0935
Epoch 164/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9511 - loss: 0.1144
Epoch 165/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9452 - loss: 0.1175
Epoch 166/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9315 - loss: 0.0985
Epoch 167/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9648 - loss: 0.0962
Epoch 168/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9569 - loss: 0.0970
Epoch 169/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9667 - loss: 0.0889
Epoch 170/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9550 - loss: 0.1187
Epoch 171/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.9784 - loss: 0.0588
Epoch 172/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9648 - loss: 0.1198
Epoch 173/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9472 - loss: 0.0941
Epoch 174/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9745 - loss: 0.0700
Epoch 175/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9765 - loss: 0.0720
Epoch 176/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9139 - loss: 0.1508
Epoch 177/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9569 - loss: 0.0864
Epoch 178/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9491 - loss: 0.0881
Epoch 179/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9550 - loss: 0.0904
Epoch 180/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9550 - loss: 0.0941
Epoch 181/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9374 - loss: 0.0916
Epoch 182/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - BinaryAccuracy: 0.9726 - loss: 0.0890
Epoch 183/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9765 - loss: 0.0986
Epoch 184/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9804 - loss: 0.0825
Epoch 185/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9217 - loss: 0.1390
Epoch 186/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9569 - loss: 0.0774
Epoch 187/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9589 - loss: 0.0820
Epoch 188/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9550 - loss: 0.0999
Epoch 189/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9589 - loss: 0.0862
Epoch 190/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9784 - loss: 0.0728
Epoch 191/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9667 - loss: 0.0786
Epoch 192/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9667 - loss: 0.0740
Epoch 193/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - BinaryAccuracy: 0.9550 - loss: 0.0734
Epoch 194/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9784 - loss: 0.0864
Epoch 195/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9765 - loss: 0.1071
Epoch 196/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9941 - loss: 0.0603
Epoch 197/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9765 - loss: 0.0902
Epoch 198/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9550 - loss: 0.0879
Epoch 199/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9706 - loss: 0.0712
Epoch 200/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9589 - loss: 0.0646
Epoch 201/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9256 - loss: 0.1364
Epoch 202/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9511 - loss: 0.1166
Epoch 203/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9667 - loss: 0.0718
Epoch 204/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9530 - loss: 0.0740
Epoch 205/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0754
Epoch 206/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9726 - loss: 0.0626
Epoch 207/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9667 - loss: 0.0689
Epoch 208/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9843 - loss: 0.0649
Epoch 209/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9843 - loss: 0.0646
Epoch 210/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9628 - loss: 0.0730
Epoch 211/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9608 - loss: 0.0802
Epoch 212/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9002 - loss: 0.1632
Epoch 213/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9706 - loss: 0.0669
Epoch 214/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9843 - loss: 0.0584
Epoch 215/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9315 - loss: 0.1029
Epoch 216/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9472 - loss: 0.0914
Epoch 217/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9843 - loss: 0.0690
Epoch 218/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9648 - loss: 0.0987
Epoch 219/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9667 - loss: 0.0718
Epoch 220/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9765 - loss: 0.0736
Epoch 221/500

In [24]:
start_test = time.time()
test_loss, test_acc = model.evaluate(X_test, y_test)
end_test = time.time()
testing_time = end_test - start_test
print(f"Testing time: {testing_time:.2f} seconds")

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - BinaryAccuracy: 0.7720 - loss: 0.9309
Testing time: 0.15 seconds

In [25]:
y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
(43, 1)
(43,)

In [26]:
# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.7674418604651163
Confusion Matrix:
 [[22  3]
 [ 7 11]]
Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.88      0.81        25
           1       0.79      0.61      0.69        18

    accuracy                           0.77        43
   macro avg       0.77      0.75      0.75        43
weighted avg       0.77      0.77      0.76        43

In [27]:
# 3. We are using adagrad optimizer :
model.compile(loss=tf.keras.losses.BinaryCrossentropy(), optimizer='adagrad', metrics=['BinaryAccuracy'])

start_train = time.time()
history = model.fit(X_train, y_train, epochs=500)
end_train = time.time()

training_time = end_train - start_train
print(f"Training time: {training_time:.2f} seconds")

Epoch 1/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9765 - loss: 0.0511
Epoch 2/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 1.0000 - loss: 0.0458
Epoch 3/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0431
Epoch 4/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0367
Epoch 5/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9941 - loss: 0.0265
Epoch 6/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0322
Epoch 7/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0321
Epoch 8/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0322
Epoch 9/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0412
Epoch 10/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9941 - loss: 0.0336
Epoch 11/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0366
Epoch 12/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0368
Epoch 13/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0304
Epoch 14/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0308
Epoch 15/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0390
Epoch 16/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0358
Epoch 17/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0407
Epoch 18/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0381
Epoch 19/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0366
Epoch 20/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0378
Epoch 21/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0381
Epoch 22/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0316
Epoch 23/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9941 - loss: 0.0348
Epoch 24/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0358
Epoch 25/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.9941 - loss: 0.0288
Epoch 26/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0357
Epoch 27/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0277
Epoch 28/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0318
Epoch 29/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0317
Epoch 30/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9902 - loss: 0.0287
Epoch 31/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9824 - loss: 0.0361
Epoch 32/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0378
Epoch 33/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0299
Epoch 34/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0390
Epoch 35/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0379
Epoch 36/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9941 - loss: 0.0247
Epoch 37/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0432
Epoch 38/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0285
Epoch 39/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0339
Epoch 40/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0299
Epoch 41/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9941 - loss: 0.0320
Epoch 42/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9902 - loss: 0.0292
Epoch 43/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0430
Epoch 44/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9941 - loss: 0.0284
Epoch 45/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0375
Epoch 46/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0331
Epoch 47/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0409
Epoch 48/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0354
Epoch 49/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0265
Epoch 50/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0349
Epoch 51/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0394
Epoch 52/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0383
Epoch 53/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9941 - loss: 0.0267
Epoch 54/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9941 - loss: 0.0278
Epoch 55/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9941 - loss: 0.0303
Epoch 56/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9941 - loss: 0.0277
Epoch 57/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.9824 - loss: 0.0392
Epoch 58/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0283
Epoch 59/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0375
Epoch 60/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9824 - loss: 0.0393
Epoch 61/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0411
Epoch 62/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0339
Epoch 63/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0373
Epoch 64/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0327
Epoch 65/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0310
Epoch 66/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0360
Epoch 67/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0281
Epoch 68/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0380
Epoch 69/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0403
Epoch 70/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9902 - loss: 0.0283
Epoch 71/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0348
Epoch 72/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0283
Epoch 73/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0307
Epoch 74/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0249
Epoch 75/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0287
Epoch 76/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9941 - loss: 0.0270
Epoch 77/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0335
Epoch 78/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0404
Epoch 79/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9902 - loss: 0.0283
Epoch 80/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0275
Epoch 81/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0375
Epoch 82/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9941 - loss: 0.0311
Epoch 83/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0360
Epoch 84/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0423
Epoch 85/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0263
Epoch 86/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0403
Epoch 87/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0329
Epoch 88/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0442
Epoch 89/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.9824 - loss: 0.0381
Epoch 90/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0331
Epoch 91/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0348
Epoch 92/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - BinaryAccuracy: 0.9902 - loss: 0.0299
Epoch 93/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0369
Epoch 94/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - BinaryAccuracy: 0.9902 - loss: 0.0303
Epoch 95/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0381
Epoch 96/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0421
Epoch 97/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0357
Epoch 98/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9902 - loss: 0.0310
Epoch 99/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9902 - loss: 0.0345
Epoch 100/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - BinaryAccuracy: 0.9902 - loss: 0.0292
Epoch 101/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0305
Epoch 102/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9902 - loss: 0.0331
Epoch 103/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0387
Epoch 104/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0252
Epoch 105/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0420
Epoch 106/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0309
Epoch 107/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0323
Epoch 108/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9824 - loss: 0.0391
Epoch 109/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0267
Epoch 110/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0373
Epoch 111/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9941 - loss: 0.0215
Epoch 112/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0277
Epoch 113/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0311
Epoch 114/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9941 - loss: 0.0342
Epoch 115/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9824 - loss: 0.0403
Epoch 116/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0371
Epoch 117/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9902 - loss: 0.0348
Epoch 118/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9941 - loss: 0.0235
Epoch 119/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0298
Epoch 120/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0264
Epoch 121/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0358
Epoch 122/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.9902 - loss: 0.0300
Epoch 123/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0332
Epoch 124/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0316
Epoch 125/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9902 - loss: 0.0301
Epoch 126/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.9824 - loss: 0.0379
Epoch 127/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.9902 - loss: 0.0320
Epoch 128/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0315
Epoch 129/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9941 - loss: 0.0274
Epoch 130/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0364
Epoch 131/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0383
Epoch 132/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0390
Epoch 133/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0358
Epoch 134/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0278
Epoch 135/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0336
Epoch 136/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9824 - loss: 0.0414
Epoch 137/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0267
Epoch 138/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0274
Epoch 139/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.9902 - loss: 0.0322
Epoch 140/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.9824 - loss: 0.0373
Epoch 141/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0416
Epoch 142/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0362
Epoch 143/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0353
Epoch 144/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0240
Epoch 145/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0286
Epoch 146/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0209
Epoch 147/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0331
Epoch 148/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9902 - loss: 0.0289
Epoch 149/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0269
Epoch 150/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0243
Epoch 151/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0258
Epoch 152/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0346
Epoch 153/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9824 - loss: 0.0365
Epoch 154/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0327
Epoch 155/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - BinaryAccuracy: 0.9824 - loss: 0.0411
Epoch 156/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0388
Epoch 157/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0339
Epoch 158/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0319
Epoch 159/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0256
Epoch 160/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0338
Epoch 161/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0356
Epoch 162/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0331
Epoch 163/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0294
Epoch 164/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0274
Epoch 165/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9902 - loss: 0.0244
Epoch 166/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0283
Epoch 167/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0252
Epoch 168/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0254
Epoch 169/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0269
Epoch 170/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0274
Epoch 171/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0349
Epoch 172/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9902 - loss: 0.0332
Epoch 173/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0326
Epoch 174/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9941 - loss: 0.0284
Epoch 175/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0364
Epoch 176/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0271
Epoch 177/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9941 - loss: 0.0309
Epoch 178/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0375
Epoch 179/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - BinaryAccuracy: 0.9941 - loss: 0.0273
Epoch 180/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0315
Epoch 181/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0357
Epoch 182/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9941 - loss: 0.0241
Epoch 183/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9902 - loss: 0.0331
Epoch 184/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - BinaryAccuracy: 0.9902 - loss: 0.0337
Epoch 185/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - BinaryAccuracy: 0.9824 - loss: 0.0346
Epoch 186/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0336
Epoch 187/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0418
Epoch 188/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - BinaryAccuracy: 0.9824 - loss: 0.0345
Epoch 189/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9824 - loss: 0.0377
Epoch 190/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9902 - loss: 0.0342
Epoch 191/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0300
Epoch 192/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0321
Epoch 193/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0305
Epoch 194/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0377
Epoch 195/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9902 - loss: 0.0280
Epoch 196/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0365
Epoch 197/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - BinaryAccuracy: 0.9824 - loss: 0.0361
Epoch 198/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9941 - loss: 0.0224
Epoch 199/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0356
Epoch 200/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9902 - loss: 0.0360
Epoch 201/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0388
Epoch 202/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0333
Epoch 203/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0339
Epoch 204/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9902 - loss: 0.0309
Epoch 205/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - BinaryAccuracy: 0.9824 - loss: 0.0335
Epoch 206/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0328
Epoch 207/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - BinaryAccuracy: 0.9824 - loss: 0.0360
Epoch 208/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9824 - loss: 0.0371
Epoch 209/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0371
Epoch 210/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - BinaryAccuracy: 0.9824 - loss: 0.0378
Epoch 211/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9824 - loss: 0.0370
Epoch 212/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - BinaryAccuracy: 0.9902 - loss: 0.0305
Epoch 213/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - BinaryAccuracy: 0.9902 - loss: 0.0266
Epoch 214/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - BinaryAccuracy: 0.9824 - loss: 0.0343
Epoch 215/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - BinaryAccuracy: 0.9941 - loss: 0.0287
Epoch 216/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - BinaryAccuracy: 0.9824 - loss: 0.0381
Epoch 217/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0293
Epoch 218/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - BinaryAccuracy: 0.9941 - loss: 0.0262
Epoch 219/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0298
Epoch 220/500
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - BinaryAccuracy: 0.9902 - loss: 0.0314
Epoch 221/500

In [28]:
start_test = time.time()
test_loss, test_acc = model.evaluate(X_test, y_test)
end_test = time.time()
testing_time = end_test - start_test
print(f"Testing time: {testing_time:.2f} seconds")

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - BinaryAccuracy: 0.7202 - loss: 0.8651
Testing time: 0.16 seconds

In [29]:
y_pred = model.predict(X_test)
print(y_pred.shape)
y_bi_pred = (y_pred > 0.5).astype(int).flatten()
print(y_bi_pred.shape)

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000029EE2350EA0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
1/2 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/stepWARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000029EE2350EA0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
(43, 1)
(43,)

In [30]:
# Calculating Accuracy, precision, recall, f1-score and Confusion Matrix
accuracy = accuracy_score(y_test, y_bi_pred)
conf_matrix = confusion_matrix(y_test, y_bi_pred)
class_report = classification_report(y_test, y_bi_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.7209302325581395
Confusion Matrix:
 [[20  5]
 [ 7 11]]
Classification Report:
               precision    recall  f1-score   support

           0       0.74      0.80      0.77        25
           1       0.69      0.61      0.65        18

    accuracy                           0.72        43
   macro avg       0.71      0.71      0.71        43
weighted avg       0.72      0.72      0.72        43